CREATE TABLE IF NOT EXISTS trade.user (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  created_time DATETIME NULL DEFAULT NULL,
  updated_time DATETIME NULL DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UK_ob8kqyqqgmefl0aco34akdtpe (email ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;