hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /uaa/**
        serviceId: auth-service
        stripPrefix: false
        sensitiveHeaders:

    trade-consumption:
        path: /consumption/**
        serviceId: trade-consumption
        stripPrefix: false
        sensitiveHeaders:

    trade-processing:
        path: /processing/**
        serviceId: trade-processing
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
